# Generated by Django 3.1.1 on 2021-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210401_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='blanke',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankf',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankg',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankh',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blanki',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankn',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blanks',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankt',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankv',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='blankw',
            field=models.TextField(blank=True, max_length=122, null=True),
        ),
    ]
